<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>한국IT아카데미</title>
    
    <meta name="description" content="방송콘텐츠, 정보보안, 게임콘텐츠, 웹디자인 전문가양성, NCS 과정 국비지원무료교육, 취업연계">
    <meta property="og:type" content="website">
    <meta property="og:title" content="한국IT아카데미">
    <meta property="og:description" content="방송콘텐츠, 정보보안, 게임콘텐츠, 웹디자인 전문가양성, NCS 과정 국비지원무료교육, 취업연계">
    <meta property="og:image" content="http://job.ac.kr/main_imgs/logo.jpg">
    <meta property="og:url" content="http://job.ac.kr/">
    
    <!--favicon-->
    <link rel="shortcut icon" type="/image/png" href="/images/2017/favicon.png">
    <!--plugin css-->
    <link rel="stylesheet" href="/css/2017/jquery.bxslider.css">
    <!--css-->
    <link rel="stylesheet" href="/css/2017/reset.css">
    <link rel="stylesheet" href="/css/2017/common.css">
    <link rel="stylesheet" href="/css/2017/sub-layout.css">
	<link rel="stylesheet" href="/css/2017/campusinfo.css">
	<link rel="stylesheet" href="/css/2017/hankookitacademy.css">
	<link rel="stylesheet" href="/css/2017/community.css">
	<link rel="stylesheet" href="/css/2017/vocationaltraining.css">
	<link rel="stylesheet" href="/css/2017/membership.css">
	<link rel="stylesheet" href="/css/2017/course.css">
	<link rel="stylesheet" href="/css/2017/project.css">
	<link rel="stylesheet" href="/css/2017/scrollbar.css">
	<link rel="stylesheet" href="/css/2017/cardnews.css">
    <link rel="stylesheet" href="/css/2017/license.css">
    <link rel="stylesheet" href="/css/2017/online.css">
    <link rel="stylesheet" href="/css/2018/resume.css">
    <!--링크취업성공css파일-->
    <link rel="stylesheet" href="/css/2018/jobsuccess.css">
   
     
    <!--국비과정모집-->
    <link rel="stylesheet" href="/css/2018/professionalEdu.css">
	<!--폰트어썸-->
    <link rel = "stylesheet"href = "/css/font-awesome/all.min.css">
     

     
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--js-->
    <script src="/js/prettify.js"></script>
    <script src="/js/jquery.js"></script>
    <script src="/js/2017/jquery.min.js"></script>
	<script src="/js/jquery.scrollbar.js"></script>
    <script src="/js/2017/jquery.bxslider.js"></script>
    <script src="/js/2018/lazyload.min.js"></script>
    <script src="/js/2017/leftslide.js"></script>
    <script src="/js/2018/jquery.bpopup.min.js"></script>
	
	<!-- 2018.01.08 마케팅 본부 네이버공통키(식별자) 변경 -->
	<script type="text/javascript" src="http://wcs.naver.net/wcslog.js"></script>
	    <!--네이버웹마스터sns주소등록-->
    <span itemscope="" itemtype="http://schema.org/Organization">
         <link itemprop="url" href="http://www.job.ac.kr">
             <a itemprop="sameAs" href="https://www.instagram.com/koritjob"></a>
             <a itemprop="sameAs" href="https://www.facebook.com/www.job.ac.kr"></a>
             <a itemprop="sameAs" href="https://blog.naver.com/yongtecher-bonbu"></a>
             <a itemprop="sameAs" href="http://cafe.naver.com/ayschool"></a>
    </span>

    <!--취업지원레이어팝업-->
    
    <script type="text/javascript">
        function go_popup() {

            $('#popup').bPopup();

        };

    </script>
    
    


