<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>한국IT아카데미</title>
    
    <meta name="description" content="방송콘텐츠, 정보보안, 게임콘텐츠, 웹디자인 전문가양성, NCS 과정 국비지원무료교육, 취업연계">
    <meta property="og:type" content="website">
    <meta property="og:title" content="한국IT아카데미">
    <meta property="og:description" content="방송콘텐츠, 정보보안, 게임콘텐츠, 웹디자인 전문가양성, NCS 과정 국비지원무료교육, 취업연계">
    <meta property="og:image" content="http://job.ac.kr/main_imgs/logo.jpg">
    <meta property="og:url" content="http://job.ac.kr/">
	
    <!--네이버웹마스터서포트등록-->
	
    <meta name="naver-site-verification" content="cb6b2ecc94e35a84637b389c29be88c55ff12d4b"/>
	<meta name="format-detection" content="telephone=no">
	
	
    <!--favicon-->
    <link rel="shortcut icon" type="/image/png" href="/images/2017/favicon.png">
	
    <!--plugin css-->
    <link rel="stylesheet" href="/css/2017/jquery.bxslider.css">
	
    <!--css-->
    <link rel="stylesheet" href="/css/2017/reset.css">
    <link rel="stylesheet" href="/css/2017/common.css">
    <link rel="stylesheet" href="/css/2017/mainStyle.css">
	<link rel="stylesheet" href="/css/2017/scrollbar.css">
	<link rel="stylesheet" href="/css/2018/cloud.css">
	<link rel="stylesheet" type="text/css" href="/css/2018/slick.css"/>
	<link rel="stylesheet" type="text/css" href="/css/2018/slick-theme.css"/>

	
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	
    <!--js-->
	<script src="/js/prettify.js"></script>
    <script src="/js/jquery.js"></script>
    <script src="/js/2017/jquery.min.js"></script>
	<script src="/js/jquery.scrollbar.js"></script>
    <script src="/js/2017/jquery.bxslider.min.js"></script>
	<script src="/js/2018/lazyload.min.js"></script>
    <script src="/js/2017/leftslide.js"></script>
	
    <script type="text/javascript" src="/js/2017/slick.js"></script>
				
   
    

    <!--map반응형-->
    <script src="/js/2017/jquery.rwdImageMaps.min.js"></script>
    
    <!-- 2018.01.08 마케팅 본부 네이버공통키(식별자) 변경 -->
	<script type="text/javascript" src="http://wcs.naver.net/wcslog.js"></script>
	
    <!--네이버웹마스터sns주소등록-->
    <span itemscope="" itemtype="http://schema.org/Organization">
         <link itemprop="url" href="http://www.job.ac.kr">
             <a itemprop="sameAs" href="https://www.instagram.com/koritjob"></a>
             <a itemprop="sameAs" href="https://www.facebook.com/www.job.ac.kr"></a>
             <a itemprop="sameAs" href="https://blog.naver.com/yongtecher-bonbu"></a>
             <a itemprop="sameAs" href="http://cafe.naver.com/ayschool"></a>
    </span>
