
<style>
#QuickWrap .Sns ul{width:300px}
#QuickWrap .Sns ul li {
    width: 25%;
    float: left;
    padding: 0px 0;
    border-right: none
}
</style>
		<div id="QuickWrap">
		    <div class="Sns">
		        <span class="title">한국IT SNS</span>
		        <ul>
		            <li>
		                <a href="https://www.facebook.com/koreaitbest/" target="_blank">
		                    <div class="image">
		                        <img class="lazy" src="/images/2020/fb_icon.png" alt="페이스북"></div>
		                    <!--<div class="txt">페이스북</div>-->
		                </a>
		            </li>
		            <li>
		                <a href="https://www.youtube.com/channel/UCMwF4Le8uyrh9GNKZKwPCjg/featured" target="_blank">
		                    <div class="image">
		                        <img class="lazy" src="/images/2020/youtube_icon.png" alt="유튜브"></div>
		                    <!--<div class="txt" >유튜브</div>-->
		                </a>
		            </li>
		            <li>
		                <a href="https://m.blog.naver.com/PostList.nhn?permalink=permalink&blogId=ji5516&proxyReferer=http:%2F%2Fm.koreait.ac.kr%2F2018%2Findex.asp" target="_blank">
		                    <div class="image">
		                        <img class="lazy" src="/images/2020/blog_icon.png" alt="네이버블로그"></div>
		                    <!--<div class="txt lh08">네이버블로그</div>-->
		                </a>
		            </li>
		            <li>
		                <a href="https://www.instagram.com/?hl=ko" target="_blank">
		                    <div class="image">
		                        <img class="lazy" src="/images/2020/insta_icon.png" alt="인스타그램"></div>
		                    <!--<div class="txt lh08">인스타그램</div>-->
		                </a>
		            </li>
		            <!--<li>
						<a href="http://tv.naver.com/koreait1998" target="_blank">
							<div class="image">
							<img class="lazy" src="/images/2018/footer/tv_icon.png" alt="네이버TV"></div>
							<div class="txt" >네이버TV</div>
						</a>
					</li>-->
		            <!--<li>
						<a href="https://pf.kakao.com/_YBxixixd" target="_blank">
							<div class="image">
							<img class="lazy" src="/images/2018/footer/kakao_icon.png" alt="카카오톡"></div>
							<div class="txt" >카카오톡</div>
						</a>
					</li>-->
		        </ul>
		    </div>
		</div>